before_script:
  - composer self-update
  - composer install
services:
  - redis-server
language: php
branches:
  only:
    - master
php:
  - 7.1
script:
  - ./vendor/bin/phpunit
notifications:
  email: false
