before_script:
  - composer self-update
  - composer install
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
services:
  - redis-server
language: php
branches:
  only:
    - master
php:
  - 7.1
script:
  - ./vendor/bin/phpunit
notifications:
  email: false
